### PR TITLE
TESTS: Move actors-tests to tests/

### PR DESCRIPTION
**Pull request by metayan**
Fixes the recent failure in [http://report.quicklisp.org](http://report.quicklisp.org)
```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A10083}>:
 no symbol named "CHANL" in "CHANL"
```

### CODE REVIEW

**Comment by adlai** [comment]
Thank you for noticing the Quicklisp report, and sending this patch.

I'm hesitant to automatically merge it due to the fact that commit 49d504e intentionally removes both of the files in question from the ASDF modules, due to them currently being even more experimental than the parts of the main library that still have insufficient test coverage.

**Comment by metayan** [comment]
Alright. The commit comments weren't completely crystal clear… ;)

**Comment by adlai** [comment]
I have commented the relevant files out of the examples module, although they should still appear in any distribution of the library that was not produced by an overly unintelligent distributor; if it's considered necessary that the files be declared as static files, please reopen **this** pull request, with a commit that does so, instead of opening a new one.

**Comment by metayan** [comment]
Great. It loads cleanly now.
( I was just joking a little about the beautifully surreal commit comments before. :) )

**Comment by adlai** [comment]
> ( I was just joking a little about the beautifully surreal commit comments before. :) )

No offense taken! I prefer not to write pages of boilerplate step-by-step instructions, as though the readers have never used git or CL before, although this does often lead to inscrutability.

**Pull request closed without merging**
